name: antiberta
channels:
    - defaults
    - conda-forge
    - pytorch
    - huggingface
dependencies:
    - python==3.9
    - transformers==4.7.0
    - datasets==1.11.0
    - pandas==1.3.2
    - cudatoolkit
    - torch==1.9.0
